"""Build governed release-control artifacts for an attested GitHub workflow run."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from thesis_proposed_solution.runtime_config import (
    GoldTableConfig,
    GovernanceRefs,
    ObjectStorageConfig,
    PipelineRuntimeConfig,
    runtime_config_to_dict,
)

PIPELINE_ID = "edgar_governed_pipeline"
JOB_REFS = {
    "ingest": "jobs/ingest/edgar_ingest.py",
    "transform": "jobs/transform/edgar_transform.py",
    "quality": "jobs/quality/curated_quality_gate.py",
    "promote": "jobs/promote/promote_to_s3_table.py",
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-manifest-output", required=True)
    parser.add_argument("--change-output", required=True)
    parser.add_argument("--runtime-config-output", required=True)
    parser.add_argument("--summary-output", required=True)
    parser.add_argument("--release-id", required=True)
    parser.add_argument("--change-id", required=True)
    parser.add_argument("--artifact-bundle-path", required=True)
    parser.add_argument("--artifact-bundle-sha256", required=True)
    parser.add_argument("--artifact-attestation-bundle-path")
    parser.add_argument("--attestation-id")
    parser.add_argument("--attestation-url")
    parser.add_argument("--subject-digest")
    parser.add_argument("--github-server-url", required=True)
    parser.add_argument("--github-repository", required=True)
    parser.add_argument("--github-sha", required=True)
    parser.add_argument("--github-ref-name", required=True)
    parser.add_argument("--github-run-id", required=True)
    parser.add_argument("--github-run-attempt", required=True)
    parser.add_argument("--github-run-number", required=True)
    parser.add_argument("--github-workflow", required=True)
    parser.add_argument("--github-workflow-ref", required=True)
    parser.add_argument("--dataset-date", default="2024-01-31")
    parser.add_argument("--source-uri", default="tests/fixtures/edgar_sample/submissions.json")
    parser.add_argument("--terraform-state-ref", default="terraform-state/local-docker-airflow.json")
    parser.add_argument("--notes", default="Governed release bundle generated by GitHub Actions release controls.")
    return parser


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _relative_repo_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT_DIR.resolve()))
    except ValueError:
        return str(path)


def _repository_url(server_url: str, repository: str) -> str:
    return f"{server_url.rstrip('/')}/{repository}"


def _commit_url(server_url: str, repository: str, commit_sha: str) -> str:
    return f"{_repository_url(server_url, repository)}/commit/{commit_sha}"


def _run_url(server_url: str, repository: str, run_id: str) -> str:
    return f"{_repository_url(server_url, repository)}/actions/runs/{run_id}"


def build_runtime_config(
    *,
    dataset_date: str,
    source_uri: str,
    release_manifest_ref: str,
    terraform_state_ref: str,
    change_ref: str,
) -> PipelineRuntimeConfig:
    return PipelineRuntimeConfig(
        pipeline_id=PIPELINE_ID,
        dataset_date=dataset_date,
        source_uri=source_uri,
        object_storage=ObjectStorageConfig(
            raw_bucket="local-raw",
            raw_prefix="edgar/raw",
            curated_bucket="local-curated",
            curated_prefix="edgar/curated",
            manifest_bucket="local-manifests",
            manifest_prefix="governed-runs",
            local_base_dir=Path(".local-data/object-storage"),
            storage_mode="local",
        ),
        gold_table=GoldTableConfig(
            gold_table_bucket="local-gold-bucket",
            gold_namespace="edgar",
            gold_table="filings",
            local_tables_dir=Path(".local-data/s3-tables"),
        ),
        governance=GovernanceRefs(
            release_manifest_ref=release_manifest_ref,
            terraform_state_ref=terraform_state_ref,
            change_ref=change_ref,
        ),
    )


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    release_manifest_output = Path(args.release_manifest_output)
    change_output = Path(args.change_output)
    runtime_config_output = Path(args.runtime_config_output)
    summary_output = Path(args.summary_output)
    artifact_bundle_path = Path(args.artifact_bundle_path)
    attestation_bundle_path = Path(args.artifact_attestation_bundle_path) if args.artifact_attestation_bundle_path else None

    repository_url = _repository_url(args.github_server_url, args.github_repository)
    commit_url = _commit_url(args.github_server_url, args.github_repository, args.github_sha)
    run_url = _run_url(args.github_server_url, args.github_repository, args.github_run_id)
    source_control = {
        "git_commit_sha": args.github_sha,
        "git_branch": args.github_ref_name,
        "repository_url": repository_url,
        "commit_url": commit_url,
        "git_worktree_dirty": False,
    }
    ci_run = {
        "github_run_id": args.github_run_id,
        "github_run_attempt": args.github_run_attempt,
        "github_run_number": args.github_run_number,
        "github_run_url": run_url,
        "github_workflow": args.github_workflow,
        "github_workflow_ref": args.github_workflow_ref,
    }
    attestation = {
        "available": bool(args.attestation_id and args.attestation_url and args.subject_digest),
        "provider": "github",
        "attestation_id": args.attestation_id,
        "attestation_ref": f"gh://attestations/{args.attestation_id}" if args.attestation_id else None,
        "attestation_url": args.attestation_url,
        "subject_digest": args.subject_digest,
        "subject_path": _relative_repo_path(artifact_bundle_path),
        "github_repository": args.github_repository,
        "github_run_id": args.github_run_id,
        "github_run_url": run_url,
        "github_workflow_ref": args.github_workflow_ref,
        "commit_sha": args.github_sha,
        "sigstore_bundle_path": _relative_repo_path(attestation_bundle_path) if attestation_bundle_path else None,
    }
    artifact_bundle = {
        "path": _relative_repo_path(artifact_bundle_path),
        "sha256": args.artifact_bundle_sha256,
        "subject_digest": args.subject_digest,
        "attestation_bundle_path": _relative_repo_path(attestation_bundle_path) if attestation_bundle_path else None,
        "verified_file_sha256": _sha256_file(artifact_bundle_path),
    }

    release_manifest = {
        "release_id": args.release_id,
        "pipeline_id": PIPELINE_ID,
        "dag_bundle_ref": "pipelines/edgar_governed_pipeline.py",
        "jobs": JOB_REFS,
        "notes": args.notes,
        "generated_at": utc_now_iso(),
        "source_control": source_control,
        "ci_run": ci_run,
        "artifact_bundle": artifact_bundle,
        "attestation": attestation,
    }
    change_record = {
        "change_id": args.change_id,
        "title": f"Release controls run for {args.github_sha[:12]}",
        "source": "github-actions-release-controls",
        "generated_at": utc_now_iso(),
        "source_control": source_control,
        "ci_run": ci_run,
        "attestation": attestation,
    }

    runtime_config = build_runtime_config(
        dataset_date=args.dataset_date,
        source_uri=args.source_uri,
        release_manifest_ref=_relative_repo_path(release_manifest_output),
        terraform_state_ref=args.terraform_state_ref,
        change_ref=_relative_repo_path(change_output),
    )

    _write_json(release_manifest_output, release_manifest)
    _write_json(change_output, change_record)
    _write_json(runtime_config_output, runtime_config_to_dict(runtime_config))
    _write_json(
        summary_output,
        {
            "release_manifest_path": _relative_repo_path(release_manifest_output),
            "change_path": _relative_repo_path(change_output),
            "runtime_config_path": _relative_repo_path(runtime_config_output),
            "artifact_bundle": artifact_bundle,
            "attestation": attestation,
            "source_control": source_control,
            "ci_run": ci_run,
        },
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
